---
title: 'LSAC: Tables & Figures'
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(xfun)
library(kableExtra)
library(vtable)
library(magrittr)
```

```{r}
load("~/GitHub/veni_lsac/Outputs/plantingforest/LSAC_plantingforest_workspace2.RData")
```

Table 1. Descriptive Statistics for latent score predictors.
```{r}

predictor.scores[-1] %>% 
sumtable(out = "return",
         summ= c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)')) %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")

```

Table 2. Descriptive statistics of raw continuous variables
```{r}
single.items.df [,-1] %>% 
  select_if(is.numeric) %>% 
  sumtable(out = "return",
            summ= c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)')) %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")

```


Table 3. Descriptive statistics of categorical predictors
```{r}
single.items.df %>% 
  select_if(is.factor) %>% 
  sumtable(out = "return") %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")
```



Table 4. Ranked importance of latent score predictors and their interactions with parenting variables
```{r}
VI %>% 
  as.data.frame() %>% 
  rownames_to_column(var="var") %>%  
  arrange(-importance) %>% 
  top_n(50, wt=importance) %>% 
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

Table 5. SEM-Forest importance plot
```{r}

#res_rf <- readRDS("~/GitHub/veni_lsac/Outputs/plantingforest/full_forest_test.RData")


# cl<-makeCluster(2)
# vim <- semtree::varimp(res_rf)
# parallel::stopCluster(cl)
# 
# # saveRDS(vim, paste0("Outputs/plantingforest/vim_full_forest_test.RData"))
# # vim <- readRDS("Outputs/plantingforest/vim_full_forest_test.RData")
# 
# res_rf_VI <- list(variable.importance = semtree:::aggregateVarimp(vim, aggregate = "median", scale = "absolute", TRUE))
# class(res_rf_VI) <- "ranger"
# # saveRDS(res_rf_VI, "Outputs/plantingforest/res_rf_VI_full_forest_test.RData")
# # res_rf_VI<-readRDS("Outputs/plantingforest/res_rf_VI_full_forest_test.RData")

metaforest::VarImpPlot(res_rf_VI)
```

